# Generated by Django 2.0.4 on 2018-04-23 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_attendance', models.CharField(choices=[('PRE', 'Present'), ('LAT', 'Late'), ('ABS', 'Absent')], max_length=20)),
                ('behavior', models.CharField(choices=[('NOR', 'Normal'), ('PRO', 'Problematic')], default='normal', max_length=15)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
