# Generated by Django 2.0.4 on 2018-04-24 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='behavior',
            field=models.CharField(choices=[('NOR', 'Normal'), ('PRO', 'Problematic')], default='NOR', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='daily_attendance',
            field=models.CharField(choices=[('PRE', 'Present'), ('LAT', 'Late'), ('ABS', 'Absent')], default='PRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
