# Generated by Django 2.0.4 on 2018-04-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180424_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='users',
        ),
    ]
