# Generated by Django 2.0.4 on 2018-04-24 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_remove_attendance_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
