# Generated by Django 2.0.4 on 2018-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='ic_num',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
        ),
    ]
