# Generated by Django 2.0.4 on 2018-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180423_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ic_num',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
