# Generated by Django 2.0.4 on 2018-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180423_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ic_num',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
