# Generated by Django 2.0.4 on 2018-04-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180423_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ic_num',
            new_name='identity_number',
        ),
    ]
