# Generated by Django 2.0.4 on 2018-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_classrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classrooms',
            field=models.ManyToManyField(default='', to='classrooms.Classroom'),
        ),
    ]
