# Generated by Django 2.0.4 on 2018-04-24 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0011_classroom_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='users',
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
