# Generated by Django 2.0.4 on 2018-04-24 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_auto_20180424_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(default='', on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
    ]
