# Generated by Django 2.0.4 on 2018-04-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0013_auto_20180424_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
    ]
